const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
  await prisma.cartItem.deleteMany();
  await prisma.feature.deleteMany();
  await prisma.product.deleteMany();

  const products = [
    // ===== MEN (9) =====
    { name: "TC 7900 'SAIL'", subtitle: "MEN · SS26", price: 185, description: "Engineered for those who demand both performance and style. Lightweight knit upper, responsive SAIL Air cushioning, and a hex-rubber outsole tuned for multi-surface traction.", image: "http://localhost:3001/images/shoe-1.jpg", sizes: JSON.stringify(["7","7.5","8","8.5","9","9.5","10","10.5","11","12","13"]), weight: "248g", drop: "8mm", rating: 4.9, category: "men", colorway: "Sail / Cream White", style: "Lifestyle", featured: true },
    { name: "SAIL RUNNER FLUX", subtitle: "MEN · SS26", price: 165, description: "Built for the daily grind. Breathable engineered mesh with dual-density midsole. Lightweight, responsive, road-tested for 500+ miles.", image: "http://localhost:3001/images/shoe-2.webp", sizes: JSON.stringify(["7","7.5","8","8.5","9","9.5","10","10.5","11","12"]), weight: "225g", drop: "10mm", rating: 4.7, category: "men", colorway: "Black / Volt", style: "Running" },
    { name: "SAIL COURT LEGACY", subtitle: "MEN · FW26", price: 135, description: "Heritage court silhouette rebuilt with modern comfort. Premium tumbled leather upper, perforated toe box, vulcanized rubber cupsole.", image: "http://localhost:3001/images/shoe-3.webp", sizes: JSON.stringify(["7","8","8.5","9","9.5","10","10.5","11","12","13"]), weight: "310g", drop: "6mm", rating: 4.8, category: "men", colorway: "White / Gum", style: "Lifestyle" },
    { name: "SAIL PHANTOM X", subtitle: "MEN · SS26", price: 220, description: "Carbon-fiber plate sandwiched between dual ZoomX foam layers. Sub-6oz race weight. Built to break personal records.", image: "http://localhost:3001/images/shoe-4.webp", sizes: JSON.stringify(["7","7.5","8","8.5","9","9.5","10","10.5","11"]), weight: "168g", drop: "8mm", rating: 4.9, category: "men", colorway: "Hyper Royal / White", style: "Racing", featured: true },
    { name: "SAIL DUNK LOW RETRO", subtitle: "MEN · FW26", price: 120, salePrice: 89, description: "The icon returns. Padded low-cut collar, classic perforated leather upper, traditional cupsole. Streetwear essential.", image: "http://localhost:3001/images/shoe-5.avif", sizes: JSON.stringify(["7","7.5","8","8.5","9","9.5","10","10.5","11","12","13"]), weight: "340g", drop: "4mm", rating: 4.6, category: "men", colorway: "Panda / Black White", style: "Lifestyle" },
    { name: "SAIL TRAIL TERRA", subtitle: "MEN · SS26", price: 175, description: "Aggressive Vibram outsole, GORE-TEX waterproof membrane, reinforced toe cap. Mountain trails to city streets.", image: "http://localhost:3001/images/shoe-6.avif", sizes: JSON.stringify(["8","8.5","9","9.5","10","10.5","11","12"]), weight: "295g", drop: "6mm", rating: 4.7, category: "men", colorway: "Olive / Earth Brown", style: "Trail" },
    { name: "SAIL AIR MAX PULSE", subtitle: "MEN · SS26", price: 195, salePrice: 149, description: "Maximum visible Air meets modern design. Full-length Air unit, gradient mesh upper, reflective 3M accents.", image: "http://localhost:3001/images/shoe-7.avif", sizes: JSON.stringify(["7","7.5","8","8.5","9","9.5","10","10.5","11","12"]), weight: "312g", drop: "12mm", rating: 4.8, category: "men", colorway: "Pure Platinum / Red", style: "Lifestyle", featured: true },
    { name: "SAIL SLIDE COMFORT", subtitle: "MEN · SS26", price: 55, description: "Recovery starts here. Contoured foam footbed, textured traction outsole, adjustable strap.", image: "http://localhost:3001/images/shoe-8.avif", sizes: JSON.stringify(["7","8","9","10","11","12","13"]), weight: "145g", drop: "0mm", rating: 4.5, category: "men", colorway: "Black / Anthracite", style: "Slides" },
    { name: "SAIL BLAZER MID", subtitle: "MEN · FW26", price: 110, salePrice: 79, description: "Original mid-top. Canvas and suede, vintage exposed foam tongue, vulcanized herringbone outsole.", image: "http://localhost:3001/images/shoe-9.avif", sizes: JSON.stringify(["7","7.5","8","8.5","9","9.5","10","10.5","11","12"]), weight: "365g", drop: "6mm", rating: 4.6, category: "men", colorway: "Sail / Midnight Navy", style: "Lifestyle" },

    // ===== WOMEN (9) =====
    { name: "SAIL AURA WMNS", subtitle: "WMNS · SS26", price: 175, description: "Sculpted silhouette designed around the female foot. Narrower heel, wider forefoot, plush collar foam. Effortless all-day wear.", image: "http://localhost:3001/images/shoe-10.avif", sizes: JSON.stringify(["5","5.5","6","6.5","7","7.5","8","8.5","9","10"]), weight: "215g", drop: "8mm", rating: 4.9, category: "women", colorway: "Rose Whisper / White", style: "Lifestyle", featured: true },
    { name: "SAIL SWIFT WMNS", subtitle: "WMNS · SS26", price: 155, description: "Lightweight racer built for speed sessions. Breathable mono-mesh, propulsion plate, ultra-responsive foam stack.", image: "http://localhost:3001/images/shoe-11.avif", sizes: JSON.stringify(["5","5.5","6","6.5","7","7.5","8","8.5","9"]), weight: "185g", drop: "6mm", rating: 4.8, category: "women", colorway: "Barely Volt / White", style: "Running", featured: true },
    { name: "SAIL PLATFORM CLASSIC", subtitle: "WMNS · FW26", price: 130, description: "Court classic elevated. 40mm platform midsole, premium leather, embossed heel logo. Statement meets comfort.", image: "http://localhost:3001/images/shoe-12.avif", sizes: JSON.stringify(["5","5.5","6","6.5","7","7.5","8","8.5","9","10"]), weight: "335g", drop: "4mm", rating: 4.7, category: "women", colorway: "Triple White", style: "Lifestyle" },
    { name: "SAIL FLEX TRAINER", subtitle: "WMNS · SS26", price: 115, salePrice: 85, description: "Gym-to-street versatility. Flat stable base, flexible forefoot grooves, breathable upper, internal midfoot cage.", image: "http://localhost:3001/images/shoe-13.avif", sizes: JSON.stringify(["5","5.5","6","6.5","7","7.5","8","8.5","9"]), weight: "230g", drop: "4mm", rating: 4.6, category: "women", colorway: "Lilac / Grey", style: "Training" },
    { name: "SAIL TRAIL BLOOM", subtitle: "WMNS · SS26", price: 165, description: "Nature-inspired trail runner. Recycled ripstop upper, aggressive lugged outsole, waterproof membrane. Bloom in any weather.", image: "http://localhost:3001/images/shoe-14.avif", sizes: JSON.stringify(["5.5","6","6.5","7","7.5","8","8.5","9"]), weight: "265g", drop: "6mm", rating: 4.7, category: "women", colorway: "Forest Green / Cream", style: "Trail" },
    { name: "SAIL DUNK LOW WMNS", subtitle: "WMNS · FW26", price: 120, salePrice: 95, description: "Women's-exclusive colorway on the timeless Dunk. Soft leather, padded collar, flat rubber outsole.", image: "http://localhost:3001/images/shoe-15.avif", sizes: JSON.stringify(["5","5.5","6","6.5","7","7.5","8","8.5","9","10"]), weight: "315g", drop: "4mm", rating: 4.8, category: "women", colorway: "Pink Glaze / White", style: "Lifestyle" },
    { name: "SAIL CLOUD WALKER", subtitle: "WMNS · SS26", price: 145, description: "Walking shoe reimagined. Triple-stack cushion, rocker geometry, slip-on design. Like walking on actual clouds.", image: "http://localhost:3001/images/shoe-1.jpg", sizes: JSON.stringify(["5","6","6.5","7","7.5","8","8.5","9","10"]), weight: "198g", drop: "10mm", rating: 4.9, category: "women", colorway: "Cloud White / Soft Pink", style: "Lifestyle", featured: true },
    { name: "SAIL SLIDE VELVET", subtitle: "WMNS · SS26", price: 65, description: "Luxe recovery slide. Velvet strap, contoured arch support, ultra-soft foam footbed. Après everything.", image: "http://localhost:3001/images/shoe-2.webp", sizes: JSON.stringify(["5","6","7","8","9","10"]), weight: "130g", drop: "0mm", rating: 4.5, category: "women", colorway: "Mauve / Gold", style: "Slides" },
    { name: "SAIL REACT INFINITY", subtitle: "WMNS · SS26", price: 170, salePrice: 129, description: "Injury-reducing design. Wide base, rocker sole, React foam. Built for runners who never want to stop.", image: "http://localhost:3001/images/shoe-3.webp", sizes: JSON.stringify(["5","5.5","6","6.5","7","7.5","8","8.5","9"]), weight: "245g", drop: "9mm", rating: 4.8, category: "women", colorway: "Sunset Orange / White", style: "Running" },

    // ===== KIDS (8) =====
    { name: "SAIL JUNIOR FORCE", subtitle: "KIDS · SS26", price: 75, description: "Built tough for the playground. Durable leather upper, easy velcro closure, flexible rubber outsole. Adventure-proof.", image: "https://images.unsplash.com/photo-1724921195451-148259c080cb?w=800&q=80&fit=crop&auto=format", sizes: JSON.stringify(["10C","11C","12C","13C","1Y","2Y","3Y"]), weight: "165g", drop: "6mm", rating: 4.8, category: "kids", colorway: "White / Royal Blue", style: "Lifestyle", featured: true },
    { name: "SAIL LIL RUNNER", subtitle: "KIDS · SS26", price: 65, description: "First steps to fast strides. Lightweight mesh, cushioned insole, no-tie elastic laces. Made for moving kids.", image: "https://images.unsplash.com/photo-1742390671647-bc9c5399fdf3?w=800&q=80&fit=crop&auto=format", sizes: JSON.stringify(["8C","9C","10C","11C","12C","13C","1Y"]), weight: "120g", drop: "4mm", rating: 4.7, category: "kids", colorway: "Bright Crimson / Black", style: "Running" },
    { name: "SAIL DUNK LOW GS", subtitle: "KIDS · FW26", price: 85, salePrice: 65, description: "Grade school Dunk. Same iconic design, sized for growing feet. Padded collar, durable leather.", image: "https://images.unsplash.com/photo-1634151223530-6ad602d66e86?w=800&q=80&fit=crop&auto=format", sizes: JSON.stringify(["3.5Y","4Y","4.5Y","5Y","5.5Y","6Y","6.5Y","7Y"]), weight: "280g", drop: "4mm", rating: 4.6, category: "kids", colorway: "Panda / Black White", style: "Lifestyle" },
    { name: "SAIL TINY STEPS", subtitle: "TODDLER · SS26", price: 45, description: "For the littlest explorers. Soft sole, wide opening, machine washable. First shoe perfected.", image: "https://images.unsplash.com/photo-1704900264961-0bef31eada4d?w=800&q=80&fit=crop&auto=format", sizes: JSON.stringify(["2C","3C","4C","5C","6C","7C","8C","9C","10C"]), weight: "75g", drop: "2mm", rating: 4.9, category: "kids", colorway: "Pastel Rainbow", style: "Lifestyle", featured: true },
    { name: "SAIL COURT JR", subtitle: "KIDS · FW26", price: 70, description: "Court ready for young ballers. Ankle support, herringbone traction, cushioned midsole. Game time.", image: "https://images.unsplash.com/photo-1724921195454-b9996a34b5c9?w=800&q=80&fit=crop&auto=format", sizes: JSON.stringify(["3.5Y","4Y","4.5Y","5Y","5.5Y","6Y","6.5Y","7Y"]), weight: "255g", drop: "6mm", rating: 4.6, category: "kids", colorway: "Black / Laser Orange", style: "Basketball" },
    { name: "SAIL TRAIL SCOUT", subtitle: "KIDS · SS26", price: 80, description: "Young adventurer's trail shoe. Water-resistant upper, rugged outsole, protective toe bumper. Explore everything.", image: "https://images.unsplash.com/photo-1742390671604-298585775fe9?w=800&q=80&fit=crop&auto=format", sizes: JSON.stringify(["10C","11C","12C","13C","1Y","2Y","3Y"]), weight: "185g", drop: "4mm", rating: 4.7, category: "kids", colorway: "Olive / Orange", style: "Trail" },
    { name: "SAIL SLIDE JR", subtitle: "KIDS · SS26", price: 35, salePrice: 25, description: "Pool to playground. Soft foam, fun colors, easy on/off. Summer essential for kids.", image: "https://images.unsplash.com/photo-1742390671587-38df317d351d?w=800&q=80&fit=crop&auto=format", sizes: JSON.stringify(["11C","12C","13C","1Y","2Y","3Y","4Y","5Y","6Y"]), weight: "90g", drop: "0mm", rating: 4.5, category: "kids", colorway: "Aqua / Lime", style: "Slides" },
    { name: "SAIL BLAZER MID GS", subtitle: "KIDS · FW26", price: 80, description: "Mid-top style for the next generation. Canvas upper, vintage foam tongue, classic outsole.", image: "https://images.unsplash.com/photo-1657522333867-d04643ca781b?w=800&q=80&fit=crop&auto=format", sizes: JSON.stringify(["3.5Y","4Y","4.5Y","5Y","5.5Y","6Y","6.5Y","7Y"]), weight: "295g", drop: "6mm", rating: 4.6, category: "kids", colorway: "Sail / Green", style: "Lifestyle" },

    // ===== CUSTOM (6) =====
    { name: "SAIL TC 7900 ID", subtitle: "CUSTOM · SS26", price: 215, description: "Your TC 7900, your rules. Choose from 12 colorways, 4 materials, custom embroidery. One-of-one craftsmanship.", image: "http://localhost:3001/images/shoe-12.avif", sizes: JSON.stringify(["6","6.5","7","7.5","8","8.5","9","9.5","10","10.5","11","12","13"]), weight: "250g", drop: "8mm", rating: 5.0, category: "custom", colorway: "Your Choice", style: "Lifestyle", featured: true, customizable: true },
    { name: "SAIL DUNK BY YOU", subtitle: "CUSTOM · FW26", price: 160, description: "Design your Dunk from scratch. Premium leathers, suedes, and canvas. 200+ color combinations. Signed with your initials.", image: "http://localhost:3001/images/shoe-13.avif", sizes: JSON.stringify(["5","5.5","6","6.5","7","7.5","8","8.5","9","9.5","10","10.5","11","12","13"]), weight: "330g", drop: "4mm", rating: 4.9, category: "custom", colorway: "Build Your Own", style: "Lifestyle", featured: true, customizable: true },
    { name: "SAIL RUNNER ID", subtitle: "CUSTOM · SS26", price: 195, description: "Performance meets personalization. Pick your foam density, drop height, and upper material. Built for YOUR stride.", image: "http://localhost:3001/images/shoe-14.avif", sizes: JSON.stringify(["6","6.5","7","7.5","8","8.5","9","9.5","10","10.5","11","12"]), weight: "220g", drop: "Custom", rating: 4.8, category: "custom", colorway: "Configure Yours", style: "Running", customizable: true },
    { name: "SAIL BLAZER BY YOU", subtitle: "CUSTOM · FW26", price: 145, description: "The Blazer canvas is yours. Mix materials, add patches, choose your swoosh. Make it unmistakably you.", image: "http://localhost:3001/images/shoe-15.avif", sizes: JSON.stringify(["6","7","7.5","8","8.5","9","9.5","10","10.5","11","12"]), weight: "360g", drop: "6mm", rating: 4.7, category: "custom", colorway: "Design Yours", style: "Lifestyle", customizable: true },
    { name: "SAIL AIR MAX ID", subtitle: "CUSTOM · SS26", price: 230, description: "Max Air, max creativity. Transparent or opaque Air unit, gradient mesh options, reflective toggles. Your Air Max.", image: "http://localhost:3001/images/shoe-1.jpg", sizes: JSON.stringify(["6","6.5","7","7.5","8","8.5","9","9.5","10","10.5","11","12","13"]), weight: "315g", drop: "12mm", rating: 4.9, category: "custom", colorway: "Unlimited", style: "Lifestyle", featured: true, customizable: true },
    { name: "SAIL TRAIL BY YOU", subtitle: "CUSTOM · SS26", price: 205, description: "Configure your trail weapon. Outsole aggression level, waterproof toggle, upper lockdown system. Your terrain, your shoe.", image: "http://localhost:3001/images/shoe-2.webp", sizes: JSON.stringify(["7","7.5","8","8.5","9","9.5","10","10.5","11","12"]), weight: "290g", drop: "6mm", rating: 4.8, category: "custom", colorway: "Trail Spec", style: "Trail", customizable: true },
  ];

  for (const p of products) {
    await prisma.product.create({ data: p });
  }

  const features = [
    { number: "01", category: "CUSHIONING", title: "SAIL AIR — 24MM DROP", description: "RESPONSIVE FOAM UNDERFOOT · 12% MORE ENERGY RETURN" },
    { number: "02", category: "UPPER", title: "RECYCLED KNIT MESH", description: "70% POST-CONSUMER YARN · BREATHABLE 4-WAY STRETCH" },
    { number: "03", category: "OUTSOLE", title: "HEX RUBBER GRID", description: "MULTI-SURFACE TRACTION · WET & DRY TESTED" },
  ];
  for (const f of features) {
    await prisma.feature.create({ data: f });
  }

  const counts = {};
  for (const p of products) { counts[p.category] = (counts[p.category] || 0) + 1; }
  const saleCount = products.filter(p => p.salePrice).length;
  console.log(`Seeded: ${products.length} total products`);
  console.log(`  Men: ${counts.men}, Women: ${counts.women}, Kids: ${counts.kids}, Custom: ${counts.custom}`);
  console.log(`  On Sale: ${saleCount} items`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
